# Generated by Django 4.0.1 on 2024-09-25 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant', '0022_alter_bulkuploadfile_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='merchant_follower_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
