# Generated by Django 4.0.1 on 2025-01-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0023_seller_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='declined_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
