# Generated by Django 4.0.1 on 2025-02-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0024_seller_declined_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('approve', 'Approve'), ('checked', 'Checked'), ('declined', 'Declined')], default='pending', max_length=20, null=True),
        ),
    ]
