# Generated by Django 4.0.1 on 2024-10-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_slug'),
        ('account', '0019_profile_following'),
    ]

    operations = [
#        migrations.AlterField(
#            model_name='profile',
#            name='following',
#            field=models.ManyToManyField(blank=True, related_name='following_list', to='store.Store'),
#        ),
    ]
