# Generated by Django 4.0.1 on 2025-01-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0023_seller_follower'),
        ('account', '0023_profile_notifications_enabled_profile_totp_secret'),
    ]

    # operations = [
    #     migrations.RunSQL(
    #         "ALTER TABLE account_profile_following RENAME COLUMN store_id TO seller_id;"
    #         )
#        migrations.AlterField(
#            model_name='profile',
#            name='following',
#            field=models.ManyToManyField(blank=True, related_name='following_list', to='merchant.Seller'),
#        ),
    # ]
