# Generated by Django 4.0.1 on 2025-06-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0025_alter_seller_status'),
        ('account', '0025_alter_profile_following_yearlybonusrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following_list', to='merchant.Seller'),
        ),
    ]
