# Generated by Django 4.0.1 on 2025-06-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0025_alter_seller_status'),
        ('account', '0026_alter_profile_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoyaltyProgrammeWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_rolled_over', models.BooleanField(default=False)),
                ('customer_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantLoyaltyProgrammeWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_rolled_over', models.BooleanField(default=False)),
                ('merchant_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='merchant.seller')),
            ],
        ),
        migrations.RenameField(
            model_name='yearlybonusrecord',
            old_name='profile',
            new_name='customer_profile',
        ),
        migrations.AddField(
            model_name='yearlybonusrecord',
            name='merchant_profile',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.seller'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LoyaltyProgramme',
        ),
    ]
