# Generated by Django 4.0.1 on 2024-09-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0040_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True, unique=True),
        ),
    ]
