# Generated by Django 4.0.1 on 2024-10-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0041_product_choice_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
