# Generated by Django 4.0.1 on 2024-10-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0042_product_discount_end_time_product_free_shipping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productwishlist',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='orderproduct',
            name='ecommerce_o_price_7a94a5_idx',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_uid',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='ecommerce_c_user_id_530d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['cart_uid'], name='ecommerce_c_cart_ui_7feefa_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status'], name='ecommerce_c_status_a40bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='cartproduct',
            index=models.Index(fields=['cart'], name='ecommerce_c_cart_id_364cec_idx'),
        ),
        migrations.AddIndex(
            model_name='cartproduct',
            index=models.Index(fields=['product_detail'], name='ecommerce_c_product_273e85_idx'),
        ),
        migrations.AddIndex(
            model_name='cartproduct',
            index=models.Index(fields=['price'], name='ecommerce_c_price_f761b7_idx'),
        ),
        migrations.AddIndex(
            model_name='cartproduct',
            index=models.Index(fields=['quantity'], name='ecommerce_c_quantit_d52fac_idx'),
        ),
        migrations.AddIndex(
            model_name='cartproduct',
            index=models.Index(fields=['shipper_name'], name='ecommerce_c_shipper_9199e6_idx'),
        ),
        migrations.AddIndex(
            model_name='cartproduct',
            index=models.Index(fields=['company_id'], name='ecommerce_c_company_f5a5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['image'], name='ecommerce_i_image_77ad3c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['cart'], name='ecommerce_o_cart_id_853e01_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='ecommerce_o_custome_77998c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['address'], name='ecommerce_o_address_e163f1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='ecommerce_o_payment_c2da01_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['price'], name='ecommerce_o_price_d4a043_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['product_detail'], name='ecommerce_o_product_b395d2_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['shipper_name'], name='ecommerce_o_shipper_62d3aa_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['status'], name='ecommerce_o_status_03ae98_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='ecommerce_p_name_78a08e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['description'], name='ecommerce_p_descrip_90e413_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='ecommerce_p_slug_b8decd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id'], name='ecommerce_p_id_85a06b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['discount_end_time'], name='ecommerce_p_discoun_5e24c0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['choice'], name='ecommerce_p_choice_e0cc8e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sale_count'], name='ecommerce_p_sale_co_98cacf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['free_shipping'], name='ecommerce_p_free_sh_70a897_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['name'], name='ecommerce_p_name_75c86a_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['slug'], name='ecommerce_p_slug_a2f612_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['id'], name='ecommerce_p_id_d865d1_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['image'], name='ecommerce_p_image_5c63d3_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['parent'], name='ecommerce_p_parent__57c458_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['product'], name='ecommerce_p_product_d2ef49_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['price'], name='ecommerce_p_price_eaf489_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['id'], name='ecommerce_p_id_fc5284_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product_detail'], name='ecommerce_p_product_0ef2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['image'], name='ecommerce_p_image_i_a17d80_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['id'], name='ecommerce_p_id_6f3e49_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['user'], name='ecommerce_p_user_id_1c226e_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product'], name='ecommerce_p_product_943105_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['id'], name='ecommerce_p_id_8b6b00_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['rating'], name='ecommerce_p_rating_f99cee_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['review'], name='ecommerce_p_review_4a6de9_idx'),
        ),
        migrations.AddIndex(
            model_name='productwishlist',
            index=models.Index(fields=['user'], name='ecommerce_p_user_id_bde822_idx'),
        ),
        migrations.AddIndex(
            model_name='productwishlist',
            index=models.Index(fields=['product'], name='ecommerce_p_product_bb5194_idx'),
        ),
        migrations.AddIndex(
            model_name='productwishlist',
            index=models.Index(fields=['id'], name='ecommerce_p_id_2171d4_idx'),
        ),
        migrations.AddIndex(
            model_name='shipper',
            index=models.Index(fields=['name'], name='ecommerce_s_name_4ea1a0_idx'),
        ),
        migrations.AddIndex(
            model_name='shipper',
            index=models.Index(fields=['slug'], name='ecommerce_s_slug_fd3b27_idx'),
        ),
        migrations.AddIndex(
            model_name='shipper',
            index=models.Index(fields=['id'], name='ecommerce_s_id_18c6e9_idx'),
        ),
        migrations.AddIndex(
            model_name='shipper',
            index=models.Index(fields=['description'], name='ecommerce_s_descrip_41c5f2_idx'),
        ),
    ]
