# Generated by Django 4.0.1 on 2024-10-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0045_alter_productwishlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
