# Generated by Django 4.0.1 on 2024-11-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0046_cartproduct_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='shipper_image',
            field=models.ImageField(blank=True, null=True, upload_to='shipper-image'),
        ),
    ]
