# Generated by Django 4.0.1 on 2024-11-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0047_shipper_shipper_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('discard', 'Discard')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='seasonal_pick',
            field=models.BooleanField(default=False),
        ),
    ]
