# Generated by Django 4.0.1 on 2024-12-04 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0052_alter_orderproduct_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='ecommerce.productdetail'),
        ),
    ]
