# Generated by Django 4.0.1 on 2024-12-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0053_productreview_image_and_more'),
    ]

    operations = [
        # migrations.AddIndex(
        #     model_name='cart',
        #     index=models.Index(fields=['user', 'cart_uid', 'status'], name='ecommerce_c_user_id_1433fa_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='cartproduct',
        #     index=models.Index(fields=['cart', 'product_detail', 'price', 'quantity'], name='ecommerce_c_cart_id_7e67b5_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='image',
        #     index=models.Index(fields=['image'], name='ecommerce_i_image_77ad3c_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='order',
        #     index=models.Index(fields=['cart', 'customer', 'address', 'payment_status'], name='ecommerce_o_cart_id_a975f2_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='orderproduct',
        #     index=models.Index(fields=['price', 'quantity', 'discount', 'total', 'status', 'delivery_date', 'created_on', 'updated_on', 'cancelled_on', 'packed_on', 'shipped_on', 'delivered_on', 'returned_on', 'payment_on', 'refunded_on', 'request_for_return'], name='ecommerce_o_price_7a94a5_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='productimage',
        #     index=models.Index(fields=['product_detail', 'image'], name='ecommerce_p_product_b2e092_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='productreview',
        #     index=models.Index(fields=['user', 'product', 'rating', 'review'], name='ecommerce_p_user_id_366283_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='productwishlist',
        #     index=models.Index(fields=['user', 'product'], name='ecommerce_p_user_id_e131af_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='shipper',
        #     index=models.Index(fields=['name', 'slug', 'description'], name='ecommerce_s_name_cc7e75_idx'),
        # ),
    ]
