# Generated by Django 4.0.1 on 2024-12-11 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0054_cart_ecommerce_c_user_id_1433fa_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='delivery_fee',
             field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='item_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='management_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='height',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='length',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='low_stock_threshold',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='shipping_days',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='stock',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='width',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        # migrations.AddIndex(
        #     model_name='cart',
        #     index=models.Index(fields=['user', 'cart_uid', 'status'], name='ecommerce_c_user_id_1433fa_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='cartproduct',
        #     index=models.Index(fields=['cart', 'product_detail', 'price', 'quantity'], name='ecommerce_c_cart_id_7e67b5_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='image',
        #     index=models.Index(fields=['image'], name='ecommerce_i_image_77ad3c_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='order',
        #     index=models.Index(fields=['cart', 'customer', 'address', 'payment_status'], name='ecommerce_o_cart_id_a975f2_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='orderproduct',
        #     index=models.Index(fields=['price', 'quantity', 'discount', 'total', 'status', 'delivery_date', 'created_on', 'updated_on', 'cancelled_on', 'packed_on', 'shipped_on', 'delivered_on', 'returned_on', 'payment_on', 'refunded_on', 'request_for_return'], name='ecommerce_o_price_7a94a5_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='productimage',
        #     index=models.Index(fields=['product_detail', 'image'], name='ecommerce_p_product_b2e092_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='productreview',
        #     index=models.Index(fields=['user', 'product', 'rating', 'review'], name='ecommerce_p_user_id_366283_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='productwishlist',
        #     index=models.Index(fields=['user', 'product'], name='ecommerce_p_user_id_e131af_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='shipper',
        #     index=models.Index(fields=['name', 'slug', 'description'], name='ecommerce_s_name_cc7e75_idx'),
        # ),
    ]
