# Generated by Django 4.0.1 on 2025-02-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0057_cart_ecommerce_c_user_id_1433fa_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('declined', 'Declined'), ('checked', 'Checked'), ('approve', 'Approve')], default='active', max_length=10),
        ),
    ]
