# Generated by Django 4.0.1 on 2025-02-17 08:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0058_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(default='<p>No description available</p>'),
        ),
    ]
