# Generated by Django 4.0.1 on 2025-03-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_transaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='detailed_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
