# Generated by Django 4.0.10 on 2025-06-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0059_alter_product_description'),
        ('merchant', '0025_alter_seller_status'),
        ('account', '0025_alter_profile_following_yearlybonusrecord_and_more'),
        ('transaction', '0006_transaction_detailed_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_reward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_reward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mall_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_cashback', to='account.profile')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_cashback', to='merchant.seller')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.order')),
            ],
        ),
    ]
