# Generated by Django 4.0.1 on 2025-06-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_cashbacktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchanttransaction',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='merchanttransaction',
            name='customer_reward',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchanttransaction',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchanttransaction',
            name='mall_income',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchanttransaction',
            name='merchant_reward',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CashbackTransaction',
        ),
    ]
