# Generated by Django 4.0.1 on 2025-06-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_merchanttransaction_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchanttransaction',
            name='system_reward',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
    ]
