# Generated by Django 4.0.1 on 2025-06-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_merchanttransaction_system_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchanttransaction',
            name='customer_reward',
        ),
        migrations.RemoveField(
            model_name='merchanttransaction',
            name='merchant_reward',
        ),
        migrations.RemoveField(
            model_name='merchanttransaction',
            name='system_reward',
        ),
    ]
