# Generated by Django 4.0.1 on 2025-06-26 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0059_alter_product_description'),
        ('account', '0027_customerloyaltyprogrammewallet_and_more'),
        ('transaction', '0009_merchanttransaction_system_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_rewards', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.customerloyaltyprogrammewallet')),
                ('merchant_rewards', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.merchantloyaltyprogrammewallet')),
                ('merchant_transactions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.merchanttransaction')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.order')),
            ],
        ),
    ]
